[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/realtime/*"
  to = "https://chat-app-backend-31vq.onrender.com/realtime/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "https://chat-app-backend-31vq.onrender.com/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/websocket-connection/*"
  to = "https://chat-app-backend-31vq.onrender.com/websocket-connection/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://chat-app-backend-31vq.onrender.com/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://chat-app-backend-31vq.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/realtime/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"